## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np
p = [[5, 0], [0, 5]]
q = [[1, 4], [5, 1]]
print(p)
print(q)
result = np.dot(p, q)
print(result)

[[5, 0], [0, 5]]
[[1, 4], [5, 1]]
[[ 5 20]
 [25  5]]


## Write a NumPy program to compute the determinant of a given square array

In [3]:
import numpy as np
from numpy import linalg as LA
b = np.array([[5, 0], [1, 6]])
print(b)
print("Determinant of the 2-D array:")
print(np.linalg.det(b))

[[5 0]
 [1 6]]
Determinant of the 2-D array:
29.99999999999999


## Write a NumPy program to compute the cross product of two given vectors

In [4]:
import numpy as np
m1 = [[4, 0], [0, 2]]
m2= [[1, 4], [4, 4]]
print("original matrix:")
print(m1)
print(m2)
result1 = np.cross(m1, m2)
result2 = np.cross(m2, m1)
print("cross product of the two vectors(m1, m2):")
print(result1)
print("cross product of the two vectors(m2, m1):")
print(result2)

original matrix:
[[4, 0], [0, 2]]
[[1, 4], [4, 4]]
cross product of the two vectors(m1, m2):
[16 -8]
cross product of the two vectors(m2, m1):
[-16   8]


## Write a NumPy program to compute the condition number of a given matrix

In [7]:
import numpy as np
from numpy import linalg as LA
h = np.array([[5, 0, -5], [0, 5, 0], [5, 0, 5]])
print("Original matrix:")
print(h)
print("The condition number of the matrix:")
print(LA.cond(h))

Original matrix:
[[ 5  0 -5]
 [ 0  5  0]
 [ 5  0  5]]
The condition number of the matrix:
1.4142135623730951


## Write a NumPy program to compute the inverse of a given matrix

In [10]:
import numpy as np
o = np.array([[6,7],[4,1]])
print("Original matrix:")
print(o)
result =  np.linalg.inv(o)
print("Inverse of the said matrix:")
print(result)

Original matrix:
[[6 7]
 [4 1]]
Inverse of the said matrix:
[[-0.04545455  0.31818182]
 [ 0.18181818 -0.27272727]]
